### ISSUE TITLE
How to select multiple items using one query?

### ISSUE THREAD

**Issue by Rustam-Z** [hitplum/pyjsonpath#5]
Please check the screenshot below. I want the same result.
<img width="1047" alt="Screenshot 2023-01-06 at 16 30 43" src="https://user-images.githubusercontent.com/59933997/211004216-1dd98465-f802-4ee1-a456-7d3d1bce2569.png">

If I use the same selector using `pyjsonpath`, it is not working.
<img width="395" alt="Screenshot 2023-01-06 at 16 32 56" src="https://user-images.githubusercontent.com/59933997/211004534-b0deb536-9303-41a0-b0f5-cfa2289e5a04.png">

**Comment by hitplum** [comment]
It was fixed in version 1.2.3, you can update the version
